### ISSUE TITLE
Ticking tile entity causing server to crash. How do I remove the corrupt entity??

### ISSUE THREAD

**Issue by Jackmon1** [xJon/The-1.12.2-Pack#146]
**EDITED**
Please use a paste-tool: https://pastebin.com/usD0Zqdi

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1122-pack\configs\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue you can try to remove the problematic's block/entity's mod and therefor delete all of its content from your save, which might help solve the problem.
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).
4. Lastly consider simply using one of the world backups the modpack creates automatically in the `the-1122-pack\backups` folder.
