### ISSUE TITLE
galacticraft and extra planets mods arent working

### ISSUE THREAD

**Issue by SuperCharged78** [xJon/The-1.12.2-Pack#202]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no** 

**Issue description**
Description of what help is needed.
whenever I launch a rocket, there is nowhere to get except back to the overworld. there are no other planets and no moons. what do I do?

**Comment by xJon** [comment]
Since v1.1.0 with the addition of Planet Progression you're supposed to research and discover new planets & moons (instead of having all of them automatically "unlocked").
It was written in the v1.1.0 changelog, over the GitHub repository & in-game over the tier 1 rocket tooltip (https://i.imgur.com/6LjSGCp.png).
