### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by Smalfinn** [xJon/The-1.12.2-Pack#203]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: I am a huge Minecolonies fan. Being able to setup my own town with workers is just an awesome experience to have in minecraft. Starting out by gathering the required resources to set them up and then being able to reap the rewards when they do it them self. Think of it as an organic mech mod.

**Mod info & download page**
* [Link to official page](https://www.curseforge.com/minecraft/mc-mods/minecolonies)

**Comment by xJon** [comment]
Minecolonies seems like a really impressive mod but currently it won't be added because it does not fit in the modpack "theme", as it was not preset in The 1.7.10 Pack.
Also keep in mind that we try to not add too many big content mods to keep the modpack relatively light.
Feel free to add it yourself though & thank you for the suggestion!
