### ISSUE TITLE
Super Solar Panels mod

### ISSUE THREAD

**Issue by zwaper** [xJon/The-1.12.2-Pack#241]
**If your feature request is a mod suggestion:**
1. Has someone suggested this mod before: **Don't know**
2. Why should the mod be added: I really love the Solar panels mod and i would like to have even bigger solar panels for more/better energy for those who are really dedicated. I use the solar panels as my main intake of energy and since i've done all the solar panels that can be made i feel like with a bigger solar panel mod you get more opportunities to make energy.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/super-solar-panels

**Comment by xJon** [comment]
The modpack already has Advanced Solar Panels & Compact Solars.
Why would we need a third mod?

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.

**Comment by Dommain** [comment]
Compact Solars is tier 1, Advance Solar Panels is Tier 2, and Super Solar Panels is Tier 3. Tier 3 is much higher amount of energy provided while also working at night but the amount of resource required are is at the endgame state. This is nice because it lower the amount of energy generators/night storage which will reduce lag. One or two of the of the highest level is all the energy required by anyone/anything but the Molecular assembler. The biggest draw back is you will require a mountain of resources.

**Comment by BERKINC** [comment]
How can I change the energy generation in the Super Solar Panel on version 1.7.10?
