### ISSUE TITLE
Building Gadgets

### ISSUE THREAD

**Issue by Eng3llus** [xJon/The-1.12.2-Pack#292]
you asked that I post here some of the additional mods that would be cool to have so here I am. 

 I really like https://www.curseforge.com/minecraft/mc-mods/building-gadgets ~~and~~ ~~https://www.curseforge.com/minecraft/mc-mods/flux-networks~~

thanks for reading

**Comment by xJon** [comment]
(Flux Networks was suggested before over https://github.com/xJon/The-1.12.2-Pack/issues/71)

Building Gadgets is a really cool and capable mod but currently it won't be added because it doesn't really fit in the "theme" of the pack and was not present in The 1.7.10 Pack. We also try to not add too many mods to keep the modpack relatively light.
Thank you for the suggestions and feel free to add the mods yourself manually!
