### ISSUE TITLE
AE2 Memory Card not working

### ISSUE THREAD

**Issue by DocFrag** [xJon/The-1.12.2-Pack#353]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
 yes

**Information required**
1. Is the modpack crashing: no
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): --
3. Is Optifine installed or any other additional mods: yes (optifine)

**Describe the issue**

When i take a fresh clean crafted Memorycard and sneak + rightclick onto an p2p tunnel it says "New device configuration created and copied to memory card." but at the same time it says "Memory card cleared.". If i just rightclick it says "Invalid Machine.". Because of this, I'm not able to link 2 p2p Tunnels together. I tried removing offhand item also.

**Comment by Rihadist** [comment]
Are you in morph while trying this?

**Comment by DocFrag** [comment]
> Are you in morph while trying this?

no

**Comment by Rihadist** [comment]
If you are having the bug that I think you are, this issue should not persist in single player, only on a multiplayer server. Unfortunately, from what I can tell, there is a disagreement between AE2 and Forge on who's bug it is. As far as I can tell from issue threads I have seen, this bug is still not fixed. There are a few solutions that work for some people. This thread might help you:  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4123#issuecomment-596250634

**Comment by xJon** [comment]
I'm pretty sure @Rihadist is correct. I'll mark this as `wontfix` for now, as this is not an issue in the modpack. You can try to use the workaround posted in the link.
