### ISSUE TITLE
Server Crashed. Crash file included. Need help asap please! Cheers.

### ISSUE THREAD

**Issue by Voleogaming** [xJon/The-1.12.2-Pack#361]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
*yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **/ no** 

**Issue description**
Description of what help is needed.

Server Crashes on launch crash log made.
[crash-2020-04-20_19.20.50-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4505504/crash-2020-04-20_19.20.50-server.txt)

**Comment by Rihadist** [comment]
Try allocating more ram it seems like you only have 1gb allocated

**Comment by Voleogaming** [comment]
Thank you for your email, the max I really want to go is 2gb as it’s just a
server for a few of my mates. Would that work?

**Comment by Rihadist** [comment]
Go the max you possibly can, this pack is very resource-heavy because of all the mods. I have allocated 12gb on my dedicated server with 4 people. While 2gb is enough for a vanilla server with not too many people, for this pack it will be really rough trying to play on it. It will only get worse when you explore new areas and load more chunks, so I would recommend that you use at least 5gb.

**Comment by Voleogaming** [comment]
Okay thank you very much for your help!

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
