### ISSUE TITLE
Tinker‘s Tool Leveling

### ISSUE THREAD

**Issue by hades6400** [xJon/The-1.12.2-Pack#372]
**If your feature request is a mod suggestion:**
Yes

**1. Has someone suggested this mod before:** 
Yes

**2. Why should the mod be added:**
1. It's part of Tinkers Construct.
2. The reasons the other 2 persons have brought up, and also
it's not a big mod, so it won't affect the loading time too much.
3. There are too less modify slots and too many modify possibilities. (Some modifiers even have levels, which need 1 modifiy slot each)
4. More modifiers would create more powerful, and more fun weapons.

**Link to Tinker‘s Tool Leveling on CurseForge:**
https://www.curseforge.com/minecraft/mc-mods/tinkers-tool-leveling

**Comment by xJon** [comment]
Hi, as mentioned beforehand, the mod won't be added due to balance issues - you can read that in the first line of the mod's description.
That being said, The 1.12.2 Pack does offer 2 extra optional modifiers using this mod: https://github.com/xJon/The-1.12.2-Pack/issues/23
Feel free to add the mod yourself though, and thanks for the suggestion!
