### ISSUE TITLE
Server Worldcontrol Fatal Error

### ISSUE THREAD

**Issue by DMaxGug** [xJon/The-1.12.2-Pack#405]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?
 yes
3. Are you using Java 8, 64-bit?
yes

**Information required**
1. Is the modpack crashing: yes
2. Crash/latest log *link* https://pastebin.com/LrP4euP8
3. Is Optifine installed or any other additional mods: no

**Describe the issue**

I have a refinery set up in the Galacticraft asteroids dimension, powered by an actively cooled Extreme Reactors generator. Problem wasn't immediate, but after a few days the crash began. Server starts normally and runs with nobody in it. As soon as a player enters and the world is rendered, it immediately stops. Crash log says it's something to do with the Worldcontrol info panel.

**Comment by xJon** [comment]
1. If you're crashing due to a problematic block or entity, you can try setting these two settings to true in `the-1122-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```
2. If this doesn't solve the issue you can try to remove the problematic's block/entity's mod and therefor delete all of its content from your save, which might help solve the problem.
3. If this does not work still you can try to manually use NBTExplorer as seen in [this tutorial](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

Additionally, I will forward the bug to the mod author.

**Comment by DMaxGug** [comment]
Thanks! I'll try this and let you know.

**Comment by DMaxGug** [comment]
Option 1 worked. I was able to join the server and break the offending block, no performance issues. Again, thanks!

**Comment by xJon** [comment]
:)
