### ISSUE TITLE
Mining laser and BoP gems

### ISSUE THREAD

**Issue by SlappersOnly** [xJon/The-1.12.2-Pack#444]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder))

3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Just thought I would highlight the blacklisting attempts of gems and the current method to still spawn them/bypass the blacklist.

The Ore World Gen of gems Ruby, Topaz, Amber, Peridot, Malachite, Sapphire and Tanzanite have been blacklisted From Biomes of Plenty and ProjectRed. Most of the related recipes have also been removed. That’s fine. 

The problem is with the industrial foregoing mining laser and the Biome Finder from Biomes of Plenty. The laser will still mine those gems, the ender amethysts and the biome Essences (I also found biome essences ores generates in the End) that are needed to craft the biome finder. Personally, that’s great. Even with the gems disabled, I was able to still find a way to craft a biome finder and find unique  biomes. The problem however is for the 99% of other people using the mining laser with no intention of making a biome finder. They will start to collect hundreds and thousands of these blacklisted useless gems that can only be used to make a biome finder.

I don’t know what the ideal solution should be but just thought I would report it.

**Comment by xJon** [comment]
I understand your point, but you need to know that apart from basic ProjectRed tools, no recipes using the gems were disabled - indeed their only usage was to craft the Biome Finder.
It was planned that in the future there'll be a new custom recipe for it, but for now the gems were supposed to be creative only.

Regarding the Laser Drill, recently there was an update that reset the its configs and I must've overlooked the Biomes O' Plenty ones. This will be fixed in the next update, thank you!
