### ISSUE TITLE
Mod reccomendation: Robotic Parts (Cyberware port for 1.12.2)

### ISSUE THREAD

**Issue by a231** [xJon/The-1.12.2-Pack#50]
1: Has someone suggested this mod before: yes (i did, on Discord)

2: Cyberware is an extremely unique mod that adds a new layer of customization to the game, it allows you to switch your body parts with mechanic you, giving you new abilities (with some drawbacks, and sustaining your mechanical parts requires energy, you also cannot use too many mechanical parts)

Mod info & download page

Link to official page: https://www.curseforge.com/minecraft/mc-mods/roboticparts

**Comment by xJon** [comment]
Hi, Cyberware does look really cool - I really like the gameplay concept of switching *body parts* instead of *armor* (especially with Cyberpunk 2077 coming), but the modpack already has Modular Powersuits, which offers a similar concept. We really do not want to add too many mods as we want to maintain *relatively* light performance demands.
Feel free to add it yourself though, and thank you for the suggestion!
