### ISSUE TITLE
Ores macerate to give 2 ore dust instead of 2 crushed ore dust

### ISSUE THREAD

**Issue by NeutralEsque** [xJon/The-1.12.2-Pack#503]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes (technic launcher)
2. Are you using a computer with 8GB or more of RAM?
yes (16GB)
3. Are you using Java 8, 64-bit?
yes

**Information required**
1. Is the modpack crashing:
no
2. Crash/latest log
N/A
3. Is Optifine installed or any other additional mods:
no

Since updating to 1.2.1, ores give 2 ore dust when macerated, instead of 2 crushed ore. Backdating to 1.2.0 strangely has no effect and ores continue to give 2 ore dust.

**Comment by xJon** [comment]
This probably happens due to the fix of https://github.com/xJon/The-1.12.2-Pack/issues/461.
I thought that UniDict wouldn't mind IC2 taking advantage of its custom recipes feature, but it seems it is an issue.
We might have to add [IC2 Tweaker](https://www.curseforge.com/minecraft/mc-mods/ic2-tweaker) instead and rely on it, hoping it does not clash with UniDict's compatibility changes.

**Comment by xJon** [comment]
IC2 Macerator recipes will be fixed in the next update, hopefully releasing in the next couple of days.
