### ISSUE TITLE
Zombie Flesh doesn't contain Thaumcraft's Humanus element/energy

### ISSUE THREAD

**Issue by Bodydiver** [xJon/The-1.12.2-Pack#518]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
* yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
** yes**.

 N/A

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: ** no**

**Describe the issue**
Zombie flesh doesn't contain the humanus element that is typically included in thaumcraft 6.
A clear and concise description of what the issue is.
no source of humanus element of thaumcraft

**Comment by xJon** [comment]
This is a bug with Thaumcraft conflicting with other mods, as seen over https://github.com/Azanor/thaumcraft-beta/issues/1619. There is a chance other items are also missing their aspects.
Will look into adding the aspects back manually.

**Comment by xJon** [comment]
It seems as @tterrag1098 made a patch mod which fixes the problem over https://github.com/FTBTeam/FTB-Revelation-2/issues/277#issue-472491261, yet is currently unavailable for public redistribution.
I will leave the issue open for now and hope that the patch mod will be uploaded to CurseForge, because manually adding all of the missing item aspects seems to not be the best solution to this.

**Comment by xJon** [comment]
This will be marked as `wontfix` for now. It is possible to manually use [this patch](https://assets.tterrag.com/ThaumcraftRecipeFix-1.12.2-1.1.0.0.jar).
