### ISSUE TITLE
LAG LIKE IF I WAS IN A SERVER

### ISSUE THREAD

**Issue by Edoo2710** [xJon/The-1.12.2-Pack#557]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes*
2. Are you using a computer with 8GB or more of RAM?
yes.
3. Are you using Java 8, 64-bit?
yes.

**Issue description**
Guys, i'm playing a singleplayer map, but sometimes i get some "lag" like if i was in a server (items have a delay to pick them up, monsters moving many blocks at once, etc.).
Is this something common in this modpack?

**Comment by xJon** [comment]
This probably means your computer can't handle 20 ticks per second in your world.
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/). You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.
You are also encouraged to manually add Optifine in order to increase performance.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen with the required info.
