### ISSUE TITLE
Okay just need help because when trying to host a server the Launch.bat says "Unable to open .jar" Aka it refuses to let me run it. Any tips?

### ISSUE THREAD

**Issue by RileyEndymion** [xJon/The-1.12.2-Pack#578]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**.

**Information required**
1. Is the modpack crashing: **yes / no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **yes (list) / no**

**Describe the issue**

A clear and concise description of what the issue is.

**Comment by xJon** [comment]
Please post your `fml-server-latest.log` file using a [paste-tool](http://paste.ubuntu.com/).

**Comment by HugoZink** [comment]
There won't be an `fml-server-latest.log` file (or any log file whatsoever) since the jar file isn't starting at all.

Have you tried running the server from a different folder? Try making a new folder directly on your C: or D: drive, call it `1122packserver`, put the server software in there and run it.

**Comment by xJon** [comment]
Closed due to inactivity.
Will reopen if requested.
