### ISSUE TITLE
Growthcraft causes Exception Ticking World

### ISSUE THREAD

**Issue by GingiiHD** [xJon/The-1.12.2-Pack#583]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log: https://paste.ubuntu.com/p/9mCDHC6Mv3/
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
My server keeps crashing with this error report and I have no idea what to do about it

**Comment by GingiiHD** [comment]
I broke a grape vine and it appears to be working now, very strange haha

**Comment by xJon** [comment]
Strange, glad you got it working nonetheless. I will be sure to forward this to the mod authors, thank you for reporting!

**Comment by Jeffmagma** [comment]
Hi, I am having the exact same issue but since I only load into the server for at most 10 seconds before it crashes again, I don't have time to find the grapevine. I also can't seem to get the modded blocks to render in MCEdit to remove the grapevine either. Has the issue happened at all after you removed it? I'm wondering if this happens to all grapevines or just one in a specific state.

**Comment by GingiiHD** [comment]
It never happened again for me, check the crash log and see what it says.
Majority of the time this bug happens it’s because there’s a mob causing it
to crash so just go to peaceful and back to whatever difficulty you’re on

**Comment by xJon** [comment]
Seems to be https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/352
