### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by issei5212** [xJon/The-1.12.2-Pack#593]
**Basic details**

1. Are you using a legitimate launcher and Minecraft account:
yes - Technic Launcher
2. Are you using a computer with 8GB or more of RAM? (How to check):
yes - 16GB of ram for computer and have dedicated 10GB of ram to Technic Launcher
3. Are you using Java 8, 64-bit? (How to check): yes - 1.8.0_271 64 Bit

**Information required**

1. Is the modpack crashing: no
2. Crash/latest log link (Where to find): 
3. Is Optifine installed or any other additional mods: no to optifine

**Describe the issue**

I'm encountering this error when downloading:
![image](https://user-images.githubusercontent.com/54430713/103108064-93efea80-461a-11eb-8de1-37e7281adf34.png)

**Comment by xJon** [comment]
Hi, does this happen downloading other 1.12.2 modpacks?
It could be due to your antivirus, or the launcher; did you try downloading the modpack from CurseForge?

**Comment by Syndrixxx** [comment]
Hi, I and **my friends** have the same problem, its forge problem, tried everything I could come up with. But even when i downloaded libraries manually the game just crashed. Its happenning on forge 1.12.2 **14.23.5.2838**(that is the last one that worked for me) and higher (didn't really tried them all but **2847** also doesnt work so the problem begins somewhere in between them), I have turned off antivirus and firewall, made an exeption in firewall and antivirus for technic launcher, uninstalled antivirus, tried to delete all mods, reinstalled modpack multiple times, reinstalled technicpack multiple times, restarted computer, reinstalled java and update it, tried other modpacks and I dont know how to download modpack from CurseForge because everytime it downloads just mods and config without bin or something so I haven't tried that. I hope this information will help u realize what's the problem so u could help us. xd

**Comment by xJon** [comment]
Hi, is this still an issue?

**Comment by Syndrixxx** [comment]
Actually, it was launcher problem, all good now.

čt 11. 3. 2021 v 20:29 odesílatel Jon ***@***.***> napsal:
