### ISSUE TITLE
Binnie's Extra Trees - multipart fences crafting conflict 

### ISSUE THREAD

**Issue by condoru7991** [xJon/The-1.12.2-Pack#673]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check]
yes - 32GB (6GB Allocated) 
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-
 yes

**Information required**
1. Is the modpack crashing:  no
2. Crash/latest log: Irrelevant
3. Is Optifine installed or any other additional mods: No

**Describe the issue**

Binnie's Extra Trees - multipart fences crafting conflict - The low fence recipe is the same as growth crafts bee house & the change recipe arrow does not show; when using mixed woods; I have tried using all oak and this works 

Works with all same type (example uses oak but tested different variants):
![image](https://user-images.githubusercontent.com/4947824/115884529-eaddc300-a446-11eb-9c8e-830ed040f242.png)
![image](https://user-images.githubusercontent.com/4947824/115884585-faf5a280-a446-11eb-9b88-b73107bcda42.png)

Does not work with mixed woods (example using the suggested recipe from nei):
![image](https://user-images.githubusercontent.com/4947824/115884731-237d9c80-a447-11eb-822e-0f7247ac684f.png)

**Comment by xJon** [comment]
Hey, thanks for reporting this - the recipe conflict will be fixed in the next update so it won't be necessary to cycle between the outputs.
Regarding the Low Fence recipe, it's a bug in the mod as there's no output even without Growthcraft present:
![image](https://user-images.githubusercontent.com/8945347/115968275-c0bbfc00-a53f-11eb-8069-ff9d6203415b.png)

This bug was already reported to the mod author over https://github.com/ForestryMC/Binnie/issues/651 but it doesn't seem like it's going to be fixed soon unfortunately, so I will close this issue for now.
