### ISSUE TITLE
Processing ExtraPlanets ore outputs incompatible ingots 

### ISSUE THREAD

**Issue by kumarohaize** [xJon/The-1.12.2-Pack#682]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes 

**Information required**
1. Is the modpack crashing: Nope
2. Crash/latest log *link* Unrelated to this report 
3. Is Optifine installed or any other additional mods: No

**Describe the issue**
Tier 8 rockets from Galacticraft Extra Planets require compressed Zinc plates from a compressor or Electric Compressor. It looks like the recipe is currently only set up to take ingotZinc from Extra Planets, but not ingotZinc from Railcraft. The ore double, triple, quadruple+ process from Mekanism ends up with ingotZinc from Railcraft, but these ores can't be used in compressors or Electric Compressors to make compressed zinc plates. Every other ore with Extra Planets has worked with the Mekanism gear up until this Tier of rockets.

The same thing happens if you do get working compressed zinc plates and try to use them to make "Heavy-Duty Plate" (Tier 8). The Zinc Ingots from Railcraft can't be used in the recipe, and it looks like it wants the Extra Planets ingots only.

**Comment by xJon** [comment]
ExtraPlanets accepts only its own ingots for progression purposes, and you're getting the wrong ingots after processing because of ore dictionary unifying by UniDict.

The current workaround is to switch the ingot types using the Forge Lexicon book or the Oredictionificator.

We will apply a fix to prevent some unification done by UniDict and to allow the ores to be processed into the correct ingots.
An exception to this fix is actually the batteries (which you reported over https://github.com/xJon/The-1.12.2-Pack/issues/683) due to an issue with ExtraPlanets (https://github.com/MJRLegends/ExtraPlanets/issues/662) so for now, use the Forge Lexicon workaround for lead ingots.
