### ISSUE TITLE
Improved compatibility between crushers and compressors of different mods.

### ISSUE THREAD

**Issue by Noobly-Walker** [xJon/The-1.12.2-Pack#726]
Some things need to be defined.

Crusher-type: Something that grinds. Some of the things crusher-type machines can do is:
- X Ore => X Dust (for things that need to be smelted)
- X Ore => X (for things that work fresh from the rock)
- X => X Dust
- X Plate => X Dust
- Cobblestone => Gravel
- Gravel => Sand

Compression-type: Something that applies pushing force to things. Some of the things compression-type machines can do is:
- X Dust => X (Glowstone and Obsidian)
- X => X Plate

My issue here is that there are incompatibilities with this, especially regarding Dust and Plates in Compression-type and Crusher-type machines.
- Mekanism Glowstone and Obsidian Ingots can only made in Mekanism Osmium Compressor(1).
- Galacticraft Compressed Metal(2) can only be produced in Galacticraft Compressor(1).
- JAOPCA Plates(3) can only be made from an ingot/gem in Thermal Expansion Compactor or IndustralCraft 2 Compressor.
- JAOPCA Plates(3) can only be ground into powder in IndustralCraft 2 Macerator.

The following is a list of all machines which need their recipe lists combined.

**Crusher-type machines**
- IndustralCraft 2: Macerator
- Thermal Expansion: Pulverizer
- Advanced Machines: Rotary Macerator(4)

**Compression-type machines**
- IndustralCraft 2: Compressor
- Mekanism: Osmium Compressor(1)
- Galacticraft: Compressor(1)

(1) There are multiple upgraded versions of these machines that, according to JEI, use the same recipe lists.
(2) Compressed Metal is functionally the same as Plates. They should be crafted in the same way, and used in the same recipes as Plates.
(3) Most JAOPCA plates and other items are unlisted in JEI. There could be more incongruities involving that mod.
(4) This apparently uses the same recipe list as the Macerator from IndustralCraft 2.

**Comment by xJon** [comment]
> (1) There are multiple upgraded versions of these machines that, according to JEI, use the same recipe lists.
(4) This apparently uses the same recipe list as the Macerator from IndustralCraft 2.

I don't really understand the issue here? upgraded versions of machines usually offer better performance, but with the same recipes. If you can provide a specific example it'd be helpful.

> (2) Compressed Metal is functionally the same as Plates. They should be crafted in the same way, and used in the same recipes as Plates.
(3) Most JAOPCA plates and other items are unlisted in JEI. There could be more incongruities involving that mod.

Even though we could combine all the compressed metals from different machines using JAOPCA, avoiding this is more of a feature than a bug. There is subjective value, in leading the player to use different mods' machines for different results from each corresponding mod. Instead of having one compressor for everything, you are encouraged to invest in each mod's "technology" to get the mod's benefits.

I can see how this might be inconvenient, and you are welcome to apply the changes you suggest, but for now we prefer to leave this as-is to follow the trend we had for the past 7 years starting with The 1.7.10 Pack.
Thank you nonetheless for bringing this up!
