### ISSUE TITLE
Breaking digital miner causes it to vanish entirely

### ISSUE THREAD

**Issue by slugbaitsoul** [xJon/The-1.12.2-Pack#746]
This morning in the mining dimension I broke my digital miner.  Instead of dropping so I could pick it up, it completely vanished.  I tried quitting and restarting, but it was not there.

I looked at the logs and there was the following message (don't know if it is related):

A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.

This message fires constantly.

Secondly, since I started playing this mod, the game would occasionally crash when going through dimensions (such as nether, end or mining dimension).  The crash message would say 'unknown' instead of listing a mod that had caused the crash.

Please let me know if you need any other details, and I'll try to have debugging logging on from now on to try and trace these problems.

I am running with 9 gigs of RAM roughly, on an AMD ryzen 7 5800h processor, nvidia rtx 3060 graphics card.

**Comment by xJon** [comment]
Similar thing was reported for the Digital Miner over https://github.com/xJon/The-1.12.2-Pack/issues/644 but I never managed to reproduce the issue. If you can find steps to reproduce this maybe we could try to fix the issue.
Regarding the crashes, unfortunately this might be due to VoxelMap which has been causing some trouble. You can experiment by removing it and using a different minimap mod!

**Comment by slugbaitsoul** [comment]
I think I figured it out.  I broke the Digital Miner with my Atomic Disassembler set to Extended Vein Mining.  When I do this, the Digital Miner just vanishes.  When I mine it and the Atomic Disassembler is set to anything else, the Digital Miner drops like normal.
