### ISSUE TITLE
GC: Nuclear battery uncraftable with thermal lead

### ISSUE THREAD

**Issue by Noobly-Walker** [xJon/The-1.12.2-Pack#747]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: N/A

Galacticraft nuclear batteries are crafted using 8 galacticraftplanets:basic_item_venus:1 "Lead Ingot" and 1 galacticraftplanets:basic_item_venus:2 "Radioisotope Core". 
galacticraftplanets:"Lead Ingot" was intended to be obtained by smelting galacticraftplanets:venus:8 "Galena Ore" in a furnace. However, this yields thermalfoundation:material:8 "Lead Ingot" instead, likely due to oredict.

Modify the recipe to use thermalfoundation:"Lead Ingot" instead.

**Comment by xJon** [comment]
Thank you for the report! Hopefully you know that for now you can use the Forge Lexicon (from the Akashic Tome) to exchange different ore dictionary ingots.

**Comment by xJon** [comment]
I actually understand now that the lack of ore dictionary support is intentional there. Galacticraft lead was missing due to UniDict's ingot unification, but it is a part of the mod's progression (you can see more over: https://wiki.micdoodle8.com/wiki/Lead_Ingot).
It is a bit annoying Galacticraft uses the same ingot name as a lot of other mods do for its own progression. I might revert this change whilst making UniDict not unify lead ingots from different mods.
