### ISSUE TITLE
Thaumcraft Osmotic Enchanter Bug

### ISSUE THREAD

**Issue by Clytemn** [xJon/The-1.12.2-Pack#765]
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
The issue is that the pack does not contain Thaumcraft's version of smokey (black) quartz, only botania's version. This matters because the osmotic enchanter checks for thaumcraft's smokey (black) quartz when you attempt to enchant and if it is not there merely eats your crystals and doesn't enchant the item. I have read that other players are having this problem and the fix was switching from botania's version (smokey) to Thaumcraft's (black). When I go into the Thaumonomicon and look at the instructions to build it says I need "Block of Black Quartz" from the "Thaumic Tinkerer's mod" but that block does not exist in this pack and, while you can craft the structure, it will not allow you to properly use it without these blocks. 

Thank you for your time and for the amazing modpack!

**Comment by xJon** [comment]
Thank you for the report! It is unfortunate that Thaumic Tinkerer does not seem to be ore dictionary compatible. It seems this issue was already reported to the authors of Thaumic Tinkerer, but that the fix was never publicly released (https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/1015).

We could add a recipe for the Thaumic Tinkerer block of black quartz, but will that solve the issue, or does one also need Thaumcraft's quartz? If so that would be a problem as Thaumcraft registers its quartz only if it also generates in the world, which would not be useful to many players.

**Comment by Clytemn** [comment]
I don't know of anything that needs Thaumcraft's quartz at the moment, The block of black quartz seems to me to be the only thing that it is selective about. I have been able to craft other thaumcraft things with just the regular vanilla quartz but if I notice anything else I'll be sure to report it.

Thanks a bunch for the speedy reply and for keeping this pack up to date!

**Comment by xJon** [comment]
In this case, if by the time of the next modpack update Thaumic Tinkerer doesn't fix the incompatibility, we will introduce a recipe for its block of black quartz, to hopefully fix this issue.
