### ISSUE TITLE
VoxelMap incompatibility w/ Entity Culling causing crashes when opening full map

### ISSUE THREAD

**Issue by lordmalefico** [xJon/The-1.12.2-Pack#795]
Information:

- Im using official minecraft;
- Have a pc with 24 gb of RAM and Im using 6 gb allocated to the modpack;
- I have the java 8 64-bit;
- The modpack is crashing;
- I dont have optifine.

The Issue:

So the problem is, everytime I try to open the map the game crashes, after that I recieve a message that indicates that the mod causing the crash is the Entity Culling one.

I´ll leave a screenshot of the message, aswell as the log and the crash report files attached to this bug report.

![Entity Culling Crash](https://user-images.githubusercontent.com/96056081/178105752-32d5dffb-554b-4fbc-8bbc-280019632e36.png)
[2022-07-09-1.log](https://github.com/xJon/The-1.12.2-Pack/files/9076489/2022-07-09-1.log)
[crash-2022-07-09_12.56.40-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/9076492/crash-2022-07-09_12.56.40-client.txt)

**Comment by xJon** [comment]
If you manually remove the mod, or update it to [this](https://www.curseforge.com/minecraft/mc-mods/entity-culling/files/3777319) version, does it resolve your issue?

**Comment by lordmalefico** [comment]
> If you manually remove the mod, or update it to [this](https://www.curseforge.com/minecraft/mc-mods/entity-culling/files/3777319) version, does it resolve your issue?

Well I had to remove the mod in question because the newer version of the mod wouldnt allow me to load the modpack,

In terms of crashes, the game doesnt crash when I open the map anyomore, so problem solved.

Thank you very much for your help!!

**Comment by xJon** [comment]
Glad you resolved the issue! Still somewhat troubling Entity Culling seems incompatible, you might get slightly worse performance.
If you'd like, you can share the latest crash report so we can forward all those details to the mod's author.

**Comment by lordmalefico** [comment]
> Glad you resolved the issue! Still somewhat troubling Entity Culling seems incompatible, you might get slightly worse performance. If you'd like, you can share the latest crash report so we can forward all those details to the mod's author.

Hi,

Im sorry for the late reply.

The latest crash report I have is the one I attached in the 1st message, there you can find the log aswell, hope it can help the mod´s author :D

**Comment by xJon** [comment]
I meant the crash with the newer version of the mod as you mentioned you weren't able to load the modpack with it :)

**Comment by xJon** [comment]
It appears that this is an incompatibility of VoxelMap and Entity Culling.
You can remove either of those mods to avoid this issue.

**Comment by xJon** [comment]
@lordmalefico How often do you experience this crash?

**Comment by lordmalefico** [comment]
@xJon Im so sorry for the late reply, but due to the fire´s that have been afecting Portugal this summer, the infrastructure that makes my internet function burn down unfortunatly, and only now I´ve been able to acess the web again.

In response to your question, it usually happens when I have alot of stuff built in the save Im playing on, If I were to create a brand new world this problem woudnt occour, but after a certain amount of stuff is crafted it starts to crash practicly every time I open the map.

**Comment by xJon** [comment]
No worries about the late reply, take care!
Regarding the issue, I'm not sure what I can do about it. It seems to be an incompatibility between Entity Culling and VoxelMap. To confirm, can you manually remove Entity Culling and see if the crash still occurs?

**Comment by lordmalefico** [comment]
> No worries about the late reply, take care! Regarding the issue, I'm not sure what I can do about it. It seems to be an incompatibility between Entity Culling and VoxelMap. To confirm, can you manually remove Entity Culling and see if the crash still occurs?

I doesnt occur once I remove the entety culling mod, it works normally.

**Comment by xJon** [comment]
Seems to also happen to @Spore4ever quite often. Did this bug always happen to you? How long have you been playing the modpack?
I'm asking because Entity Culling has been a part of the modpack for over a year.

**Comment by Rishum-P** [comment]
We have a very large town on our server with a significant amount of micro blocks, which can trigger the Entity Culling crash at least 90% of the time upon entering and flying around. We normally tell players who want to enter it to remove Entity Culling. So was able to test as requested somewhat quickly: 

| Entity Culling Version| Crash| Frequency | Crash Log |
| ------------- | ------------- |  ------------- | ------------- | 
| Mod Removed | No  | N/A | N/A |
| 4.2.5 | Yes | High | [Crash-4.2.5.txt](https://github.com/xJon/The-1.12.2-Pack/files/9415300/Crash-4.2.5.txt)
| 5.3.3 | Yes | High | [Crash-5.3.3-Default.txt](https://github.com/xJon/The-1.12.2-Pack/files/9415109/Crash-5.3.3-Default.txt)|
| 5.3.3 with OpenGL Culling disabled | Yes | Low | [Crash-5.3.3-OpenGL-Disabled.txt](https://github.com/xJon/The-1.12.2-Pack/files/9415138/Crash-5.3.3-OpenGL-Disabled.txt) |

The issue seems most frequently when an area on a voxel map is generated for the first time. After the area has been loaded, it seems to happen far less frequently. It seems to also happen less frequently with OpenGL Culling disabled. However, it's hard to tell if that's coincidental or the change's effect. The issue does not just happen when opening the Minimap, but that can trigger it.

It just seems to be general incompatablity with voxel map when rendering certain things.

**Comment by lordmalefico** [comment]
> Seems to also happen to @Spore4ever quite often. Did this bug always happen to you? How long have you been playing the modpack? I'm asking because Entity Culling has been a part of the modpack for over a year.

I've been playing the modpack since 2018 I think (2019 Im not sure), and I dont remember this happening back in the day.

**Comment by xJon** [comment]
@lordmalefico It's probably due to placing some microblocks or other things in the world that cause the crash due to the incompatibility.

@Rishum-P What has been your experience running the modpack without Entity Culling so far?

**Comment by xJon** [comment]
No longer an issue in `1.5.1` because of the removal of Entity Culling due to the VoxelMap incompatibility. If someone is using a different map mod, feel free to re-add it.
