### ISSUE TITLE
Does Binnies extra trees work?

### ISSUE THREAD

**Issue by MystikReasons** [xJon/The-1.12.2-Pack#881]
Hi @xJon 

Hope you are doing fine!

I noticed in HadEnoughItems that there were many wood sorts which I have never seen in my world before and all of them are from the mod Binnies extra trees.
The only one which I have found in my world was the cherry wood
My question is, are these trees spawning in the world or is that only something for creative use?

Many thanks!

**Comment by xJon** [comment]
That's a good question! Binnie's Extra Trees is an addon mod to Forestry, and both of these mods add many new and colorful types of trees and wood types.
A few of them naturally generate in the world, but in order to obtain the rest the player needs to do tree breeding, also known as Arboriculture.
You can read more about it over the in-game Forestry guide-book, or over https://ftb.fandom.com/wiki/Arboriculture, or perhaps by looking it up on Youtube :)

**Comment by MystikReasons** [comment]
Many thanks for the detailed answer, now its clear for me :)
