### ISSUE TITLE
Craches related with searching stuff on Had Enough Items

### ISSUE THREAD

**Issue by lordmalefico** [xJon/The-1.12.2-Pack#906]
Information:

- Im using official minecraft;
- Have a pc with 24 gb of RAM and Im using 6 gb allocated to the modpack;
- I have the java 8 64-bit;
- The modpack is crashing;
- I dont have optifine.

The Issue:

So the following happens, when I try to search @Thermal on the Had Enough Items search bar the game automaticly crashes.

Ill leave the Log, the crash report and the messages that the games shows when the crash occours.

Hope we can fix this :)

[crash-2023-09-02_21.39.38-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/12504768/crash-2023-09-02_21.39.38-client.txt)
https://mclo.gs/TBskLoZ

[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/12504769/latest.log)

![Message of the Crash](https://github.com/xJon/The-1.12.2-Pack/assets/96056081/4c260c2d-c64b-4ac6-b21f-8d86c56d0b76)

**Comment by xJon** [comment]
Hmm, I can't reproduce this on `1.5.5`. Are you playing on a server with plugins?

**Comment by lordmalefico** [comment]
Im playing on a server that I think uses plugins (1122apocgaming.org),and they were using the 1.5.4 version, maybe this doesnt happen on the newer one.

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Nivid-IT** [comment]
This will be due to the fact that they have Cursed Earth disabled in the EU2 config, and JEI is trying to render items that have Cursed Earth as part of its crafting recipe, specifically Thermal Dynamics Item Covers. 

You need to clear your JEI search bar as follows:

1. Close your 1.12.2 Pack Client
2. navigate to %appdata%\Roaming\.technic\modpacks\the-1122-pack\config\jei
3. Open `worldSettings.cfg` with a text editor
4. Make sure that all instances of `S:filterText=` are empty, that means no text after the EQUALS sign.
5. Save the file, and then start up your client again.

I've encountered the exact same issue after briefly disabling Cursed Earth server-side so I'm fairly confident this will be of help for you too.

**Comment by lordmalefico** [comment]
Thanks the help, in the mean time I had reached some of the server staff about this issue, and they gave this solution as well, and yes it works, thx for the help anyways :)

Enviado de Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
